services:
  api:
    build: .
    image: playhub-api
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - pgsql

  pgsql:
    platform: linux/x86_64 # Required for Apple Silicon machine based
    image: postgres:13
    ports:
      - 5432:5432
#    volumes:
#      - pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: playhub
      POSTGRES_DATABASE: playhub
      POSTGRES_USER: playhub
      POSTGRES_PASSWORD: playhub

volumes:
  pgsql:
