services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: playhub-api
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - pgsql
    environment:
      DATABASE_URL: "pgsql://playhub:playhub@db:5432/playhub"

  pgsql:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: playhub
      POSTGRES_USER: playhub
      POSTGRES_PASSWORD: playhub

volumes:
  pgdata: