name: Phpunit Tests

on:
  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.12'
          extensions: mbstring, intl, pdo_pgsql
      - name: Install Composer dependencies
        run: |
            composer install --prefer-dist --no-interaction

  unit_tests1:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run PHPUnit Unit Tests
        run: |
          /home/runner/work/playhub-api/playhub-api/vendor/bin/phpunit --testsuite "Unit Tests"
  unit_tests2:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run PHPUnit Unit Tests
        run: |
          vendor/bin/phpunit --testsuite "Unit Tests"
  unit_tests3:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run PHPUnit Unit Tests
        run: |
          /vendor/bin/phpunit --testsuite "Unit Tests"
  unit_tests4:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run PHPUnit Unit Tests
        run: |
          $(pwd)/vendor/bin/phpunit --testsuite "Unit Tests"

  functional_tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run PHPUnit Functional Tests
        run: |
          /home/runner/work/playhub-api/playhub-api/vendor/bin/phpunit --testsuite "Functional Tests"