name: Unit Tests

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: xdebug

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit unit tests
        run: ./vendor/bin/phpunit --testsuite "Unit Tests"