name: Phpunit Tests

on:
  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHP Cs Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run PHP Unit Unit tests
        uses: php-actions/phpunit@master
        with:
          version: 11.4.1
          configuration: phpunit.xml
          testsuite: unit

      - name: Run PHP Unit Functional tests
        uses: php-actions/phpunit@master
        with:
          version: 11.4.1
          configuration: phpunit.xml
          testsuite: functional
