name: Phpunit Tests

on:
  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: Run PHP Cs Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run PHP Unit Unit tests
        uses: php-actions/phpunit@master
        with:
          version: 11.4.1
          php_version: 8.3
          configuration: phpunit.xml
          testsuite: unit

      - name: Run PHP Unit Functional tests
        uses: php-actions/phpunit@master
        with:
          version: 11.4.1
          php_version: 8.3
          configuration: phpunit.xml
          testsuite: functional
